/* ===== الجروبات + نقل الإشراف + أرشيف العضو ===== */
let GR=[],GR_ON=0,GR_SEL='',GR_VIEW='chat',GRM=[],grUnsub=null,grmUnsub=null,GR_BUSY=0,GR_ERR='',GATT=0;
let GA=[],GA_ON=0,GA_SEL='',GAM=[],gaUnsub=null,gamUnsub=null;
const gOpen=()=>!!GR_SEL&&GR_SEL!=='create'&&GR_SEL!=='archive';
const gMem=(g,u)=>(g.members||[]).find(x=>x.uid===u)||{};
const gName=(g,u)=>{const m=gMem(g,u);return m.name||(m.username?'@'+m.username:'عضو')};
const gLetter=g=>esc(String(g.name||'ج').trim().charAt(0).toUpperCase()||'ج');
const gUnread=g=>!!g.lastBy&&g.lastBy!==ME&&tms(g.lastAt)>=(LR['g'+g.id]||0);
function groupStop(){try{grUnsub&&grUnsub();grmUnsub&&grmUnsub();gaUnsub&&gaUnsub();gamUnsub&&gamUnsub()}catch(e){}grUnsub=grmUnsub=gaUnsub=gamUnsub=null;GR_ON=0;GA_ON=0;GR=[];GA=[];GRM=[];GAM=[]}
function grmStop(){try{grmUnsub&&grmUnsub()}catch(e){}grmUnsub=null;GRM=[]}
function archiveStop(){try{gaUnsub&&gaUnsub();gamUnsub&&gamUnsub()}catch(e){}gaUnsub=gamUnsub=null;GAM=[]}
async function groupInit(){
 if(GR_ON||!USER||!ME||VIEW)return;try{const{U,fs}=await fbx();archiveInit();
  const q=fs.query(fs.collection(U.db,'groups'),fs.where('memberIds','array-contains',ME));
  grUnsub=fs.onSnapshot(q,sn=>{GR=sn.docs.map(d=>Object.assign({id:d.id},d.data({serverTimestamps:'estimate'})));paintNav();if(tab==='chat'&&!GR_SEL)paintFr()},()=>{});GR_ON=1;
 }catch(e){GR=[]}}
async function archiveInit(){
 if(GA_ON||!USER||!ME||VIEW)return;try{const{U,fs}=await fbx(),q=fs.collection(U.db,'groupArchives',ME,'items');
  gaUnsub=fs.onSnapshot(q,sn=>{GA=sn.docs.map(d=>Object.assign({id:d.id},d.data({serverTimestamps:'estimate'}))).sort((a,b)=>tms(b.archivedAt)-tms(a.archivedAt));if(GR_SEL==='archive')render();else if(tab==='chat'&&!GR_SEL&&!CH)paintFr()},()=>{});GA_ON=1;
 }catch(e){GA=[]}}
function vGroups(){if(GR_SEL==='create')return vGroupCreate();if(GR_SEL==='archive')return GA_SEL?vArchiveChat():vArchiveList();if(gOpen())return GR_VIEW==='info'?vGroupInfo():vGroupChat();return vGroupList()}
function vGroupList(){const list=(GR||[]).slice().sort((a,b)=>tms(b.lastAt||b.createdAt)-tms(a.lastAt||a.createdAt));return `<div class="c group-list"><div class="hd" style="justify-content:space-between"><h2>👥 الجروبات <small>${list.length}</small></h2>${!VIEW?'<button onclick="openGroupCreate()">＋ جروب</button>':''}</div>${list.map(g=>`<div class="group-row" onclick="openGroup('${esc(g.id)}')"><div class="group-avatar">${gLetter(g)}</div><div class="friend-main"><div class="friend-name"><b>${esc(g.name||'بدون اسم')}</b>${gUnread(g)?'<span class="unread-dot">جديد</span>':''}</div><small class="friend-preview">${(g.memberIds||[]).length} أعضاء • ${esc(g.lastText||'ابدأوا المذاكرة 👋')}</small></div><div class="friend-meta">${g.lastAt?hmt(tms(g.lastAt)):''}</div></div>`).join('')||'<div class="empty-group">مفيش جروبات لسه.</div>'}<button class="secondary" style="width:100%;margin-top:8px" onclick="openArchives()">📦 أرشيف الجروبات (${GA.length})</button></div>`}
function openGroupCreate(){if(VIEW)return;GR_ERR='';GR_BUSY=0;GR_SEL='create';render()}
function vGroupCreate(){const friends=FR.filter(f=>f.status==='accepted');return `<div class="c group-create-card"><div class="hd" style="justify-content:space-between"><h2>إنشاء جروب</h2><button class="x" onclick="GR_SEL='';render()">✕</button></div><input id="gnm" maxlength="60" placeholder="اسم الجروب"><textarea id="gdesc" maxlength="300" placeholder="وصف مختصر (اختياري)"></textarea><h3>أضف أصحابك</h3><small>اختار الأصدقاء اللي هيكونوا أعضاء في الجروب.</small><div class="group-friend-picks">${friends.map(f=>{const p=peer(f);return `<label class="group-friend-pick"><input type="checkbox" name="group-friend" value="${esc(p.uid)}"><span class="avatar">${avLetter(f)}</span><span><b>${pname(f)}</b><small>@${esc(p.u)}</small></span></label>`}).join('')||'<div class="empty-group">مفيش أصحاب مضافين لسه. تقدر تعمل الجروب الأول وتضيف أعضاء بعدين.</div>'}</div>${GR_ERR?`<p style="color:var(--bad)">${esc(GR_ERR)}</p>`:''}<button class="pr" onclick="createGroup()">إنشاء الجروب</button></div>`}
async function createGroup(){if(GR_BUSY||VIEW)return;const name=(($('gnm')&&$('gnm').value)||'').trim(),desc=(($('gdesc')&&$('gdesc').value)||'').trim();if(name.length<2){GR_ERR='اكتب اسم الجروب.';render();return}const chosen=Array.from(document.querySelectorAll('input[name=group-friend]:checked')).map(e=>e.value).filter((uid,i,a)=>uid!==ME&&a.indexOf(uid)===i).slice(0,19);GR_BUSY=1;try{const{U,fs}=await fbx(),now=fs.serverTimestamp(),ref=fs.doc(fs.collection(U.db,'groups')),me={uid:ME,name:USER.name||'',username:USER.username||'',role:'owner',joinedAt:Date.now()};await fs.setDoc(ref,{name,description:desc,ownerId:ME,memberIds:[ME],members:[me],createdAt:now,updatedAt:now,lastText:'',lastAt:now});if(chosen.length){const selected=chosen.map(uid=>{const f=FR.find(x=>x.status==='accepted'&&x.m.includes(uid));if(!f)return null;const p=peer(f);return{uid,name:p.n||'',username:p.u||'',role:'member',joinedAt:Date.now()}}).filter(Boolean);if(selected.length){await fs.updateDoc(ref,{memberIds:[ME,...selected.map(m=>m.uid)],members:[me,...selected],updatedAt:fs.serverTimestamp()})}}const local={id:ref.id,name,description:desc,ownerId:ME,memberIds:[ME,...chosen],members:[me,...chosen.map(uid=>{const f=FR.find(x=>x.status==='accepted'&&x.m.includes(uid)),p=f?peer(f):{};return{uid,name:p.n||'',username:p.u||'',role:'member',joinedAt:Date.now()}})],createdAt:Date.now(),updatedAt:Date.now(),lastText:'',lastAt:Date.now()};GR.push(local);GR_SEL=ref.id;GR_BUSY=0;toast('اتعمل الجروب ✓');render()}catch(e){GR_ERR='مقدرتش أعمل الجروب. اتأكد من قواعد Firebase.';GR_BUSY=0;render()}}
async function openGroup(id){if(!GR.some(g=>g.id===id))return;grmStop();GR_SEL=id;GR_VIEW='chat';GR_ERR='';const g=GR.find(x=>x.id===id);LR['g'+id]=Math.max(Date.now(),tms(g.lastAt));try{const{U,fs}=VIEW?await fbAdmin():await fbx(),q=fs.query(fs.collection(U.db,'groups',id,'messages'),fs.orderBy('createdAt','asc'),fs.limit(300));grmUnsub=fs.onSnapshot(q,sn=>{GRM=sn.docs.map(d=>Object.assign({id:d.id},d.data()));paintGroupMsgs()},()=>toast('مقدرتش أحمّل رسائل الجروب'));render()}catch(e){toast('مقدرتش أفتح الجروب')}}
function closeGroup(){grmStop();GR_SEL='';GR_VIEW='chat';render()}
function vGroupChat(){const g=GR.find(x=>x.id===GR_SEL);if(!g)return '';return `<div class="c group-chat"><div class="chat-top"><div class="hd"><button class="x" onclick="closeGroup()">→</button><div class="group-avatar">${gLetter(g)}</div><div class="xpwrap" onclick="GR_VIEW='info';render()" style="cursor:pointer"><b>${esc(g.name)}</b><small style="display:block">${(g.memberIds||[]).length} أعضاء • التفاصيل</small></div>${!VIEW&&g.ownerId===ME?`<button class="x" onclick="inviteGroup('${esc(g.id)}')">＋</button>`:''}</div></div><div class="group-messages" id="gm"></div>${VIEW?'<div class="view-only"><small>👁 وضع المشاهدة • للعرض فقط</small></div>':vCompose('g')}</div>${vReportPanel()}`}
function paintGroupMsgs(){const b=$('gm');if(!b)return;b.innerHTML=GRM.length?GRM.map(m=>`<div class="group-msg"><small><b>${esc(m.name||'عضو')}</b> • ${hmt(tms(m.createdAt))}</small><div>${messageContent(m)}${!VIEW&&m.from!==ME?`<div class="msg-actions"><button onclick="openReportMessage('${esc(GR_SEL)}','${esc(m.id||'')}','${esc(m.from)}','')">🚩 إبلاغ</button></div>`:''}</div></div>`).join(''):'<div class="empty-group">مفيش رسائل لسه.</div>';b.scrollTop=b.scrollHeight}
async function sendGroupMsg(){if(VIEW)return;const el=$('gmi'),text=(el&&el.value||'').trim(),att=ATTP;if((!text&&!att)||GR_BUSY)return;GR_BUSY=1;try{const{U,fs}=await fbx(),now=fs.serverTimestamp(),msg={from:ME,name:USER.name||USER.username||'عضو',text,createdAt:now};if(att)msg.att=att;await fs.addDoc(fs.collection(U.db,'groups',GR_SEL,'messages'),msg);await fs.updateDoc(fs.doc(U.db,'groups',GR_SEL),{lastBy:ME,lastAt:now,lastText:(text||attLabel(att)).slice(0,100),updatedAt:now});el.value='';ATTP=null;ATTM=0;attPaint()}catch(e){toast('الرسالة ما اتبعتتش')}GR_BUSY=0}
async function inviteGroup(id){if(VIEW)return;const u=(prompt('اكتب username الصديق لإضافته')||'').trim().replace(/^@/,'').toLowerCase();if(!/^[a-z0-9_]{3,30}$/.test(u))return;try{const{U,fs}=await fbx(),s=await fs.getDoc(fs.doc(U.db,'usernames',u));if(!s.exists()){toast('الاسم مش موجود');return}const uid=s.data().uid,g=GR.find(x=>x.id===id);if(!g||g.ownerId!==ME||g.memberIds.includes(uid)||g.memberIds.length>=20){toast('لا يمكن إضافة العضو');return}const p=await fs.getDoc(fs.doc(U.db,'users',uid)),d=p.exists()?p.data():{},members=(g.members||[]).concat([{uid,name:d.name||'',username:u,role:'member',joinedAt:Date.now()}]);await fs.updateDoc(fs.doc(U.db,'groups',id),{memberIds:g.memberIds.concat([uid]),members,updatedAt:fs.serverTimestamp()});toast('اتضاف للجروب ✓')}catch(e){toast('مقدرتش أضيف العضو')}}
function groupAttachmentPicker(){return ''}
function openGroupAttachment(){attToggle()}
async function sendGroupSavedCard(deck,front,back){if(!GR_SEL||VIEW)return;const d={n:deck,cards:[{f:front,b:back}]};const raw=JSON.stringify(d);ATTP={t:'deck',n:String(deck).slice(0,100),m:'deck',d:raw};await sendGroupMsg()}
function oldestMember(g,removeUid){const ms=(g.members||[]).filter(m=>m.uid!==removeUid&&(g.memberIds||[]).includes(m.uid));return ms.sort((a,b)=>(Number(a.joinedAt)||0)-(Number(b.joinedAt)||0))[0]||null}
function memberPayload(g,removeUid,newOwner){const ids=(g.memberIds||[]).filter(x=>x!==removeUid),ms=(g.members||[]).filter(m=>m.uid!==removeUid).map(m=>Object.assign({},m,{role:m.uid===newOwner?'owner':(m.role==='owner'?'member':m.role)}));return{memberIds:ids,members:ms,ownerId:newOwner||g.ownerId,updatedAt:null}}
async function archiveGroupForUser(U,fs,g,uid,reason){const aid=g.id+'_'+uid+'_'+Date.now(),now=fs.serverTimestamp();const qs=await fs.getDocs(fs.query(fs.collection(U.db,'groups',g.id,'messages'),fs.orderBy('createdAt','asc'),fs.limit(300)));const b=fs.writeBatch(U.db),parent=fs.doc(U.db,'groupArchives',uid,'items',aid);b.set(parent,{archiveId:aid,groupId:g.id,groupName:g.name||'',memberUid:uid,reason,archivedAt:now,members:g.members||[],messageCount:qs.size});qs.docs.forEach(d=>b.set(fs.doc(U.db,'groupArchives',uid,'items',aid,'messages',d.id),Object.assign({id:d.id},d.data())));await b.commit()}
async function updateGroupAfterExit(U,fs,g,uid,reason){const remaining=(g.memberIds||[]).filter(x=>x!==uid);if(!remaining.length){await groupWipe(U,fs,g.id);return}const newOwner=g.ownerId===uid?oldestMember(g,uid):null;const p=memberPayload(g,uid,newOwner&&newOwner.uid);p.updatedAt=fs.serverTimestamp();await fs.updateDoc(fs.doc(U.db,'groups',g.id),p)}
async function groupWipe(U,fs,id){for(let k=0;k<60;k++){const s=await fs.getDocs(fs.query(fs.collection(U.db,'groups',id,'messages'),fs.limit(300)));if(s.empty)break;const b=fs.writeBatch(U.db);s.docs.forEach(d=>b.delete(d.ref));await b.commit()}await fs.deleteDoc(fs.doc(U.db,'groups',id))}
async function leaveGroup(){const g=GR.find(x=>x.id===GR_SEL);if(!g||VIEW)return;if(g.ownerId===ME&&g.memberIds.length>1){const n=oldestMember(g,ME);if(!n){toast('مفيش عضو يستلم الإشراف');return}}try{const{U,fs}=await fbx();await archiveGroupForUser(U,fs,g,ME,'left');await updateGroupAfterExit(U,fs,g,ME,'left');closeGroup();toast('خرجت واتحفظ الأرشيف ✓')}catch(e){toast('مقدرتش أخرج من الجروب')}}
async function removeFromGroup(uid){const g=GR.find(x=>x.id===GR_SEL);if(!g||VIEW||g.ownerId!==ME||uid===ME)return;try{const{U,fs}=await fbx();await archiveGroupForUser(U,fs,g,uid,'removed');await updateGroupAfterExit(U,fs,g,uid,'removed');toast('اتشال العضو واتحفظ أرشيفه ✓');render()}catch(e){toast('فشل إخراج العضو')}}
function vGroupInfo(){const g=GR.find(x=>x.id===GR_SEL);if(!g)return '';const own=g.ownerId===ME&&!VIEW;return `<button onclick="GR_VIEW='chat';render()">← رجوع للمحادثة</button><div class="c"><div class="group-avatar" style="margin:auto">${gLetter(g)}</div><h2 style="text-align:center">${esc(g.name)}</h2><small style="display:block;text-align:center">المشرف: ${esc(gName(g,g.ownerId))}</small></div><div class="c"><b>الأعضاء (${g.memberIds.length})</b>${g.memberIds.map(uid=>{const m=gMem(g,uid);return `<div class="r"><div class="group-avatar" style="width:36px;height:36px">${esc(String(m.name||m.username||'?').charAt(0))}</div><div style="flex:1"><b>${esc(gName(g,uid))}</b>${uid===g.ownerId?' <span class="bdg">مشرف</span>':''}</div>${own&&uid!==ME?`<button class="bad" onclick="removeFromGroup('${esc(uid)}')">طرد</button>`:''}</div>`}).join('')}</div>${VIEW?'':`<button class="bad" style="width:100%" onclick="leaveGroup()">🚪 خروج من الجروب</button>`}`}
async function openArchives(){archiveStop();GR_SEL='archive';GA_SEL='';try{const{U,fs}=await fbx(),q=fs.collection(U.db,'groupArchives',ME,'items');gaUnsub=fs.onSnapshot(q,sn=>{GA=sn.docs.map(d=>Object.assign({id:d.id},d.data())).sort((a,b)=>tms(b.archivedAt)-tms(a.archivedAt));render()},()=>{});render()}catch(e){toast('مقدرتش أفتح الأرشيف')}}
function vArchiveList(){return `<div class="c archive-list"><div class="hd" style="justify-content:space-between"><h2>أرشيف الجروبات</h2><button class="x" onclick="GR_SEL='';archiveStop();render()">✕</button></div><p class="archive-help">الجروبات هنا نسخة خاصة بك للرجوع إلى الرسائل القديمة. حذفها لا يحذف الجروب عند الأعضاء الآخرين.</p>${GA.map(a=>`<div class="group-row archive-item"><div class="archive-open" onclick="openArchive('${esc(a.id)}')"><div class="group-avatar">👥</div><div class="friend-main"><b>${esc(a.groupName||'جروب قديم')}</b><small>${a.reason==='removed'?'تمت إزالتك':'أنت غادرت'} • ${a.messageCount||0} رسالة</small></div></div><button class="x" onclick="deleteOneArchive('${esc(a.id)}')" aria-label="حذف من الأرشيف">🗑</button></div>`).join('')||'<div class="empty-group">الأرشيف فارغ.</div>'}${GA.length?'<button class="bad" style="width:100%;margin-top:12px" onclick="deleteAllArchives()">حذف كل الأرشيف</button>':''}</div>`}
async function openArchive(id){archiveStop();GA_SEL=id;try{const{U,fs}=await fbx(),q=fs.query(fs.collection(U.db,'groupArchives',ME,'items',id,'messages'),fs.orderBy('createdAt','asc'),fs.limit(300));gamUnsub=fs.onSnapshot(q,sn=>{GAM=sn.docs.map(d=>Object.assign({id:d.id},d.data()));render()},()=>{});render()}catch(e){toast('مقدرتش أفتح الأرشيف')}}
function vArchiveChat(){const a=GA.find(x=>x.id===GA_SEL);return `<div class="c group-chat archived-chat"><div class="chat-top"><div class="hd"><button class="x" onclick="GA_SEL='';openArchives()">→</button><div class="group-avatar archived-avatar">👥</div><div class="xpwrap" style="flex:1"><b>${esc(a&&a.groupName||'جروب قديم')}</b><small style="display:block">${a&&a.reason==='removed'?'تمت إزالتك من المجموعة':'أنت غادرت هذه المجموعة'}</small></div><button class="x" onclick="archiveMenu('${esc(GA_SEL)}')" aria-label="خيارات المجموعة">⋮</button></div></div><div class="group-messages archive-messages">${GAM.map(m=>`<div class="group-msg"><small><b>${esc(m.name||'عضو')}</b> • ${hmt(tms(m.createdAt))}</small><div>${messageContent(m)}<div class="msg-actions"><button onclick="openReportArchive('${esc(GA_SEL)}','${esc(m.id||'')}','${esc(m.from||'')}')">🚩 إبلاغ عن الرسالة</button></div></div></div>`).join('')||'<div class="empty-group">مفيش رسائل محفوظة.</div>'}</div><div class="left-group-notice"><b>${a&&a.reason==='removed'?'تمت إزالتك من هذه المجموعة.':'أنت غادرت هذه المجموعة.'}</b><small>لا يمكنك إرسال رسائل جديدة هنا.</small></div></div>`}
let HIDDEN_GROUP_ARCHIVES=[];try{HIDDEN_GROUP_ARCHIVES=JSON.parse(localStorage.getItem('mzk_hidden_group_archives')||'[]')}catch(e){}
function archiveMenu(id){const action=prompt('خيارات المجموعة:\n1 - إخفاء الجروب من قائمة المحادثات\n2 - حذف النسخة المؤرشفة نهائيًا\n3 - إلغاء');if(action==='1'){if(!HIDDEN_GROUP_ARCHIVES.includes(id))HIDDEN_GROUP_ARCHIVES.push(id);try{localStorage.setItem('mzk_hidden_group_archives',JSON.stringify(HIDDEN_GROUP_ARCHIVES))}catch(e){}toast('تم إخفاء الجروب من القائمة');GR_SEL='';GA_SEL='';paintFr();render()}else if(action==='2')deleteOneArchive(id)}
async function deleteArchiveData(id){const{U,fs}=await fbx();const path=fs.collection(U.db,'groupArchives',ME,'items',id,'messages');for(let i=0;i<20;i++){const sn=await fs.getDocs(fs.query(path,fs.limit(400)));if(sn.empty)break;const b=fs.writeBatch(U.db);sn.docs.forEach(d=>b.delete(d.ref));await b.commit()}await fs.deleteDoc(fs.doc(U.db,'groupArchives',ME,'items',id));GA=GA.filter(a=>a.id!==id);HIDDEN_GROUP_ARCHIVES=HIDDEN_GROUP_ARCHIVES.filter(x=>x!==id);try{localStorage.setItem('mzk_hidden_group_archives',JSON.stringify(HIDDEN_GROUP_ARCHIVES))}catch(e){}}
async function deleteOneArchive(id){if(!confirm('حذف النسخة المؤرشفة ورسائلها من حسابك؟ لن يؤثر ذلك على بقية أعضاء الجروب.'))return;try{await deleteArchiveData(id);if(GA_SEL===id){GA_SEL='';GAM=[]}toast('تم حذف النسخة المؤرشفة');if(GR_SEL==='archive')render();else paintFr()}catch(e){toast('تعذر حذف الأرشيف. تحقق من صلاحيات Firebase')}}
async function deleteAllArchives(){if(!GA.length||!confirm('حذف كل نسخ الجروبات المؤرشفة من حسابك؟ لن يؤثر ذلك على الجروبات عند الآخرين.'))return;try{for(const a of [...GA])await deleteArchiveData(a.id);toast('تم حذف الأرشيف');render()}catch(e){toast('تعذر حذف بعض عناصر الأرشيف')}}
async function groupCleanup(U,fs,uid){let s;try{s=await fs.getDocs(fs.query(fs.collection(U.db,'groups'),fs.where('memberIds','array-contains',uid)))}catch(e){return}for(const d of s.docs){const g=Object.assign({id:d.id},d.data());try{await archiveGroupForUser(U,fs,g,uid,'account_deleted');await updateGroupAfterExit(U,fs,g,uid,'account_deleted')}catch(e){}}}

function groupPost(){if(gOpen()){paintGroupMsgs();attPaint()}}
